fix the following bug related to the update of package hmmlearn
    MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
    https://github.com/hmmlearn/hmmlearn/issues/335
    https://github.com/hmmlearn/hmmlearn/issues/340
    Traceback (most recent call last):

    [.... ]

    ValueError: Size of each quantile should be size of p: received 1, but expected 486.